---
- name: Install bind9
  yum: name={{ item }} state=latest
  with_items:
    - bind
    - bind-libs
    - bind-utils
    - libselinux-python

- name: Create log dir
  file:
    path: "/var/log/named"
    state: directory
    owner: named
    group: named

- name: Config to bind9
  template: src={{ item }} dest=/etc/{{ item }} mode=0640 owner=root group=named
  with_items:
    - named.conf
    - named.rfc1912.zones
  notify: 
    - Restart named daemon

- name: Add zone databases
  copy: src={{ item }}.zone dest=/var/named/{{ item }}.zone mode=0640 owner=root group=named 
  with_items: "{{ zones_list }}"
  notify:
    - Reload named daemon
